version: "3.1"

# docker 구동 : docker-compose -f ... up -d
# redis-cli 실행 : docker exec -it redis_test redis-cli

# 실행하려는 컨테이너들 정의 
services:
  # 서비스 명 
  redis_contianer:
    # 사용할 이미지 
    image: redis:latest
    # 컨테이너명 
    container_name: redis_test
    # 접근 포트 설정 (컨테이너 외부 : 컨테이너 내부)
    ports:
      - 6379:6379
    # 스토리지 마운트(볼륨) 설정 
    volumes:
      - ./redis/data:/data
      - ./redis/conf/rdis.conf:/usr/local/conf/redis.conf
    # 컨테이너에 docker label 을 이용 해서 메타데이터 추가 
    labels:
      - "name=redis"
      - "model=standalone"
    # 컨테이너 종료시 재시작 여부 설정
    restart: always
    command: redis-server /usr/local/conf/redis.conf
    
